sudo: false
language: node_js
node_js:
- 6
script:
- yarn run build
deploy:
  provider: npm
  skip_cleanup: true
  email: contact@r3code.ru
  api_key:
    secure: TODO
  on:
    tags: true
    repo: r3code/vue-vis-network
