sudo: false
language: node_js
node_js:
- 6
script:
- yarn run build
deploy:
  provider: npm
  skip_cleanup: true
  email: infocontact.alex@gmail.com
  api_key:
    secure: rYsRQKdemmc4Glh3wJPOQMDmyMvGqrrnqjLXClABSBQSkatsuMobJwTcKRPlo6l9PlLMyHReZEr4PPevr0bvZQ2FGOEKD66D6g9pGY6bqkm+uEPVKorFADaDhKzmKPIm89OfL85TdBqDGcox0ywpQAjraC8Qwl4i4jElxPOTWu04nFjpHXLqxmvNdZyXzR/bDeyesST16dg2C5BopEgd/+7s02HXh9D2OHnMXFYEL48noXkcfvSeZjCm0fx7/AiZJ3LsmuwXK7hn16awi4O38qXevfUIlQ5Zt8EPz1bA8II8xInpw8szMYk8kMJ2TjvNpvWtEuHK7E8ktYLmpAk9ziKEvONkvWuoWGriuPS4ZntOHssIj5TK3fMAZU7+a144WjNN1TW1icUJMe5I2rIs5TuPe7UpweW51sBeEzwA1q77z0VrBeRJQMaEjmPoLKiWCYZGTJTeDBA5+iH2NpoAq8vm5eAmGo4YXJ3rzbOZ7Yf+NajhEzVo/MmzLQNzkppAHLu8Ssj9E5OMgn5Ih6NMKo4H0njNEszmTpW68rUsz+AyfPMe/RYCIojn9Zvbxu5Y/j/6tJau6OJ0mkjMZUXMmONNc37i7+TNyBs4lnLlq9I5Pa5alZjmq6wMivgV4ge/55Z0blpTU2JgstFjLYadzJ6/ws2haCeyCR+p69l4Vuk=
  on:
    tags: true
    repo: alexcode/vue2vis
